---
- name: restart server
  service: 
   name: httpd
   state: started
  when: ansible_os_family ==  'RedHat'

- name: restart server
  service: 
   name: apache2
   state: started
  when: ansible_os_family ==  'Debian'
